export const colNames = {
    Name: "Name",
    Year: "Year",
    PubmedID: "PubMed ID",
    Sequence: "Sequence",
    NatureType: "Synthetic/Natural",
    Source: "Source",
    Origin: "Origin",
    TaxonomicID: "Taxonomic ID",
    UniportID: "Uniport ID",
    Family: "Family",
    Length: "Length",
    Charge: "Net Charge",
    Weight: "Molecular Weight",
    PI: "PI",
    Encoding: "Linear/Cyclic",
    Nature: "Nature",
    Chirality: "Chirality",
    Structure: "3D Structure",
    NTerminal: "N-Terminal Modification",
    CTerminal: "C-Terminal Modification",
    Modification: "Chemical Modification",
    Type: "Free Living/Parasitic",
    Target: "Target Organism",
    Species: "Species",
    Strain: "Strain",
    Stage: "Stage",
    Disease: "Disease",
    Activity: "Activity",
    CellTarget: "Target Part",
    Mechanism: "Mechanism of Action",
    Hemolytic: "Hemolytic Activity",
    Cytotoxicity: "Cytotoxicity",
    Vitro_Vivo: "In Vitro/In Vivo",
    CellLine: "Cell Line",
    Model: "In Vivo Model",
    Assay: "Assay",
}

export const organisms = {
    Trypanosoma: [
        'Trypanosoma cruzi',
        'Trypanosoma brucei brucei',
        'Trypanosoma brucei rhodesiense',
        'Trypanosoma brucei gambiense',
        'Trypanosoma evansi',
        'Trypanosoma equiperdum',
        'Trypanosoma carassii',
    ],
    Leishmania: [
        'Leishmania infantum',
        'Leishmania mexicana',
        'Leishmania major',
        'Leishmania tropica',
        'Leishmania amazonensis',
        'Leishmania donovani',
        'Leishmania braziliensis',
        'Leishmania panamensis',
        'Leishmania pifanoi',
        'Leishmania aethiopica',
        'Leishmania infantum chagasi',
    ],
    Plasmodium: [
        'Plasmodium gallinaceum',
        'Plasmodium falciparum',
        'Plasmodium berghei',
        'Plasmodium yoelii nigeriensis',
        'Plasmodium yoelii',
        'Plasmodium vinckei',
    ],
    Eimeria: [
        'Eimeria tenella',
        'Eimeria acervulina',
    ],
    Babesia: [
        'Babesia bigemina',
        'Babesia equi',
    ],
    Acanthamoeba: [
        'Acanthamoeba castellanii',
        'Acanthamoeba polyphaga',
    ],
    Blastocystis: [
        'Blastocystis hominis',
        'Blastocystis spp',
    ],
    Cryptocaryon: ['Cryptocaryon irritans'],
    Toxoplasma: ['Toxoplasma gondii'],
    Miamiensis: ['Miamiensis avidus'],
    Entamoeba: ['Entamoeba histolytica'],
    Tetrahymena: ['Tetrahymena pyriformis'],
    Ichthyophthirius: ['Ichthyophthirius multifiliis'],
    Paramecium: ['Paramecium caudatum'],
    Neospora: ['Neospora caninum'],
    Trichomonas: ['Trichomonas vaginalis'],
    Besnoitia: ['Besnoitia jellisoni'],
    Cryptosporidium: ['Cryptosporidium parvum'],
    Amoeba: ['Amoeba proteus'],
    Euglena: ['Euglena gracilis'],
    Caryospora: ['Caryospora bigenetica'],
}